FROM python:3.10-slim

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker \
    dagster-gcp \
    google-cloud-bigquery \
    google-cloud-storage \
    python-dotenv \
    pandas \
    numpy

# Add code location code
WORKDIR /opt/dagster/app

# Copy all necessary files
COPY assets.py definitions.py /opt/dagster/app/
COPY ingestion /opt/dagster/app/ingestion

# Create directories for data paths
RUN mkdir -p /opt/dagster/app/data /opt/dagster/app/test_data

# Copy the .env file for environment variables
COPY .env /opt/dagster/app/.env

# Run dagster code server on port 4000
EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors to execute runs and steps
CMD ["dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-f", "definitions.py"]
